# Generated by Django 3.2 on 2021-05-29 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_thincodename_thincodeplace_thincodetotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thindevicesunits',
            name='fifty_percentgy',
        ),
        migrations.RemoveField(
            model_name='thindevicesunits',
            name='twinte_five_percentgy',
        ),
        migrations.RemoveField(
            model_name='thindevicesunits',
            name='unit',
        ),
        migrations.AddField(
            model_name='thindevicesunits',
            name='code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.thincodename'),
        ),
        migrations.AddField(
            model_name='thindevicesunits',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.thincodeplace'),
        ),
        migrations.AddField(
            model_name='thindevicesunits',
            name='total',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.thincodetotal'),
        ),
        migrations.DeleteModel(
            name='ThinUnits',
        ),
    ]
