# Generated by Django 3.2 on 2021-05-29 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_auto_20210529_0450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thindevicesunits',
            name='fifty_percentgy',
        ),
        migrations.RemoveField(
            model_name='thindevicesunits',
            name='twinte_five_percentgy',
        ),
    ]
