# Generated by Django 3.2 on 2021-05-29 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_auto_20210529_0451'),
    ]

    operations = [
        migrations.AddField(
            model_name='thindevicesunits',
            name='code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.thincodename'),
        ),
    ]
