# Generated by Django 3.2 on 2021-05-29 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_thindevicesunits_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thinunits',
            name='code',
        ),
        migrations.AlterField(
            model_name='thinunits',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.thincodename'),
        ),
        migrations.AlterField(
            model_name='thinunits',
            name='total',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.thincodetotal'),
        ),
    ]
