# Generated by Django 3.2 on 2021-05-29 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_auto_20210529_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thinunits',
            name='total',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.thincodetotal'),
        ),
    ]
