# Generated by Django 3.2 on 2021-05-29 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0012_alter_thincodename_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='thinunits',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.thincodeplace'),
        ),
    ]
