# Generated by Django 3.2 on 2021-05-29 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0013_thinunits_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thindevicesunits',
            name='added_by',
        ),
    ]
